apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32404  # Optional: Pick any free port between 30000–32767
  type: NodePort
